GET http://localhost:3001/authors
###
GET http://localhost:3001/authors?id=1
###
GET http://localhost:3001/posts
###
GET http://localhost:3001/posts/1
###
PATCH http://localhost:3001/posts/1
content-type: application/json

{"likeCount": 6}

###
GET http://localhost:3001/posts?authorId=1
###
GET http://localhost:3001/comments
###
GET http://localhost:3001/comments?authorId=1
###
GET http://localhost:3001/comments?postId=1
###
GET http://localhost:3000/api/comments?postId=1

