/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Blog API
 * API для управления постами, комментариями и авторами
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface Post {
  id: number;
  title: string;
  content: string;
  likeCount: number;
  authorId: number;
  date: string;
}

export interface PostInput {
  title: string;
  content: string;
  authorId: number;
  date: string;
}

export interface Comment {
  id: number;
  postId: number;
  authorId: number;
  content: string;
  likeCount: number;
  date: string;
}

export interface CommentInput {
  postId: number;
  authorId: number;
  content: string;
  date: string;
}

export interface Author {
  id: number;
  name: string;
}

export interface AuthorInput {
  name: string;
}

/**
 * @summary Получить все посты
 */
export const getPosts = <TData = AxiosResponse<Post[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/posts`,options
    );
  }

/**
 * @summary Создать новый пост
 */
export const createPost = <TData = AxiosResponse<Post>>(
    postInput: PostInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/posts`,
      postInput,options
    );
  }

/**
 * @summary Получить пост по ID
 */
export const getPost = <TData = AxiosResponse<Post>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/posts/${id}`,options
    );
  }

/**
 * @summary Обновить пост по ID
 */
export const updatePost = <TData = AxiosResponse<Post>>(
    id: number,
    postInput: PostInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/posts/${id}`,
      postInput,options
    );
  }

/**
 * @summary Частично обновить пост по ID
 */
export const patchPost = <TData = AxiosResponse<Post>>(
    id: number,
    postInput: PostInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/posts/${id}`,
      postInput,options
    );
  }

/**
 * @summary Удалить пост по ID
 */
export const deletePost = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/posts/${id}`,options
    );
  }

/**
 * @summary Получить все комментарии
 */
export const getComments = <TData = AxiosResponse<Comment[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/comments`,options
    );
  }

/**
 * @summary Создать новый комментарий
 */
export const createComment = <TData = AxiosResponse<Comment>>(
    commentInput: CommentInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/comments`,
      commentInput,options
    );
  }

/**
 * @summary Получить комментарий по ID
 */
export const getComment = <TData = AxiosResponse<Comment>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/comments/${id}`,options
    );
  }

/**
 * @summary Обновить комментарий по ID
 */
export const updateComment = <TData = AxiosResponse<Comment>>(
    id: number,
    commentInput: CommentInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/comments/${id}`,
      commentInput,options
    );
  }

/**
 * @summary Частично обновить комментарий по ID
 */
export const patchComment = <TData = AxiosResponse<Comment>>(
    id: number,
    commentInput: CommentInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/comments/${id}`,
      commentInput,options
    );
  }

/**
 * @summary Удалить комментарий по ID
 */
export const deleteComment = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/comments/${id}`,options
    );
  }

/**
 * @summary Получить всех авторов
 */
export const getAuthors = <TData = AxiosResponse<Author[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/authors`,options
    );
  }

/**
 * @summary Создать нового автора
 */
export const createAuthor = <TData = AxiosResponse<Author>>(
    authorInput: AuthorInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/authors`,
      authorInput,options
    );
  }

/**
 * @summary Получить автора по ID
 */
export const getAuthor = <TData = AxiosResponse<Author>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/authors/${id}`,options
    );
  }

/**
 * @summary Обновить автора по ID
 */
export const updateAuthor = <TData = AxiosResponse<Author>>(
    id: number,
    authorInput: AuthorInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/authors/${id}`,
      authorInput,options
    );
  }

/**
 * @summary Удалить автора по ID
 */
export const deleteAuthor = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/authors/${id}`,options
    );
  }

export type GetPostsResult = AxiosResponse<Post[]>
export type CreatePostResult = AxiosResponse<Post>
export type GetPostResult = AxiosResponse<Post>
export type UpdatePostResult = AxiosResponse<Post>
export type PatchPostResult = AxiosResponse<Post>
export type DeletePostResult = AxiosResponse<void>
export type GetCommentsResult = AxiosResponse<Comment[]>
export type CreateCommentResult = AxiosResponse<Comment>
export type GetCommentResult = AxiosResponse<Comment>
export type UpdateCommentResult = AxiosResponse<Comment>
export type PatchCommentResult = AxiosResponse<Comment>
export type DeleteCommentResult = AxiosResponse<void>
export type GetAuthorsResult = AxiosResponse<Author[]>
export type CreateAuthorResult = AxiosResponse<Author>
export type GetAuthorResult = AxiosResponse<Author>
export type UpdateAuthorResult = AxiosResponse<Author>
export type DeleteAuthorResult = AxiosResponse<void>
